ALTER TABLE document_master MODIFY COLUMN txn_id VARCHAR(60) NOT NULL DEFAULT '';
ALTER TABLE claim_transition MODIFY COLUMN txn_id VARCHAR(60) NOT NULL DEFAULT '';
ALTER TABLE claim_data MODIFY COLUMN txn_id VARCHAR(60) NOT NULL DEFAULT '';
ALTER TABLE claim_admission_details MODIFY COLUMN txn_id VARCHAR(60) NOT NULL DEFAULT '';
ALTER TABLE claim_module_stats MODIFY COLUMN txn_id VARCHAR(60) NOT NULL DEFAULT '';
ALTER TABLE claim_adjudication_result MODIFY COLUMN txn_id VARCHAR(60) NOT NULL DEFAULT '';
