CREATE TABLE `service_type`
(
    `id`                       bigint NOT NULL AUTO_INCREMENT,
    `service_type`             mediumtext,
    `service_type_description` mediumtext,
    `benefit_type`             varchar(50) DEFAULT NULL,
    `benefit_head`             varchar(50) DEFAULT NULL,
    `vitraya_master`           mediumtext,
    `is_enabled`               tinyint(1)  DEFAULT '0',
    PRIMARY KEY (`id`)
);

alter table claim_adjudication_result
    add column amount_approved double default null;
alter table claim_adjudication_result
    add column insurer_amount_approved double default null;

INSERT INTO `service_type`
VALUES (1, '01', 'Accommodation', 'A', 'A7', 'Room Rent', 1),
       (2, '02', 'Critical Care/ICU', 'A', 'A11', 'ICU Charges', 1),
       (3, '03', 'Operating Theatre', 'A', 'A4,A1', 'OT Charges', 1),
       (4, '04', 'Surgeon Fees', 'A', 'A1,A4', 'Professional Fees', 1),
       (5, '05', 'Anaesthetist Fees', 'A', 'A1,A4', 'Anaesthesia Charges', 1),
       (6, '06', 'Implants', 'A', 'A6', 'Implants/ Prosthetic devices', 1),
       (7, '07', 'Medicines', 'A', 'A27', 'Medicines & Consumables', 1),
       (8, '08', 'Consumables', 'A', 'A27', 'Medicines & Consumables', 1),
       (9, '09', 'Special Equipment', 'A', 'A9', 'High Risk Charges', 0),
       (10, '10', 'In Patient Package', 'A', 'A9', 'surgical package', 1),
       (11, '11', 'Day Care Package', 'C', 'C8', 'Additional Package Procedure', 1),
       (12, '13', 'Laboratory', 'A', 'A5', 'Investigation Charges', 1),
       (13, '14', 'Blood Bank', 'A', 'A5', 'Blood & Blood Products', 1),
       (14, '16', 'Radiology', NULL, NULL, 'Investigation Charges', 0),
       (15, '23', 'Consultation', 'A', 'A33', 'Investigation Charges', 1),
       (16, '24', 'OPD Treatment', NULL, NULL, 'Professional Fees', 0),
       (17, '25', 'Health Check Up', NULL, NULL, 'Investigation Charges', 0),
       (18, '26', 'Vaccination', NULL, NULL, 'Medicines & Consumables', 0),
       (19, '27', 'Maternity', 'F,N', 'F8', 'Investigation Charges', 1),
       (21, '29', 'Chemotherapy', 'C', 'C8', 'Additional Package Procedure', 1),
       (22, '30', 'Dialysis', 'C', 'C8', 'Additional Package Procedure', 1),
       (23, '31', 'Domiciliary Treatment', NULL, NULL, 'OT Charges', 0),
       (24, '33', 'Doctor\'s Visits', NULL, NULL, 'Doctor Fees', 0),
       (25, '35', 'Ambulance', 'A', 'A8', 'Ambulance Charges', 1),
       (26, '40', 'Assistance (International Roaming only)', NULL, NULL, 'Investigation Charges', 0),
       (27, '41', 'Other', 'A', 'A9', 'Others', 1),
       (28, '44', 'Assistant Surgeon', NULL, NULL, 'Medicines & Consumables', 0),
       (29, '45', 'Dental', NULL, NULL, 'Investigation Charges', 0),
       (30, '59', 'Service Charge', NULL, NULL, 'Service Tax & Other Taxes', 0),
       (31, '61', 'Administrative Charges', NULL, NULL, 'Professional Fees', 0),
       (32, '62', 'Admission Charges', NULL, NULL, 'Professional Fees', 0),
       (33, '63', 'Nursing Charges', NULL, NULL, 'Nursing Charges', 0),
       (34, '64', 'Outsourced Tests', NULL, NULL, 'Investigation Charges', 0),
       (35, '65', 'Paid by Patient (any other charges)', NULL, NULL, 'Others', 0),
       (36, '66', 'Paid by Patient (Non Payable Items)', NULL, NULL, 'Others', 0),
       (37, '67', 'Registration Charges', NULL, NULL, 'Professional Fees', 0),
       (38, '68', 'RMO Fees', NULL, NULL, 'Professional Fees', 0),
       (39, '69', 'Surcharge', NULL, NULL, 'Others', 0),
       (40, '04', 'Surgeon Fees', 'A', 'A1,A4', 'Doctor Fees', 1),
       (41, '01', 'Accommodation', 'C', 'C18', 'Room Rent', 1),
       (42, '02', 'Critical Care/ICU', 'C', 'C19', 'ICU Charges', 1),
       (43, '03', 'Operating Theatre', 'C', 'C4', 'OT Charges', 1),
       (44, '04', 'Surgeon Fees', 'C', 'C1', 'Professional Fees', 1),
       (45, '05', 'Anaesthetist Fees', 'C', 'C1', 'Anaesthesia Charges', 1),
       (46, '06', 'Implants', 'C', 'C6', 'Implants/ Prosthetic devices', 1),
       (47, '07', 'Medicines', 'C', 'C17', 'Medicines & Consumables', 1),
       (48, '08', 'Consumables', 'C', 'C17', 'Medicines & Consumables', 1),
       (49, '09', 'Special Equipment', 'C', 'C8', 'High Risk Charges', 0),
       (50, '10', 'In Patient Package', 'C', 'C9', 'surgical package', 1),
       (51, '11', 'Day Care Package', 'C', 'C9', 'Additional Package Procedure', 1),
       (52, '13', 'Laboratory', 'C', 'C5', 'Investigation Charges', 1),
       (53, '14', 'Blood Bank', 'C', 'C5', 'Blood & Blood Products', 1),
       (55, '23', 'Consultation', 'C', 'C3', 'Investigation Charges', 1),
       (60, '28', 'Radiotherapy', 'C', 'C9', 'Additional Package Procedure', 1),
       (61, '29', 'Chemotherapy', 'C', 'C9', 'Additional Package Procedure', 1),
       (62, '30', 'Dialysis', 'C', 'C9', 'Additional Package Procedure', 1),
       (64, '33', 'Doctor\'s Visits', 'C', 'C3', 'Doctor Fees', 0),
       (65, '35', 'Ambulance', 'C', 'C7', 'Ambulance Charges', 1),
       (67, '41', 'Other', 'C', 'C9', 'Others', 1),
       (70, '59', 'Service Charge', 'C', 'C8', 'Service Tax & Other Taxes', 0),
       (71, '61', 'Administrative Charges', 'C', 'C8', 'Professional Fees', 0),
       (73, '63', 'Nursing Charges', 'C', 'C16', 'Nursing Charges', 0),
       (80, '04', 'Surgeon Fees', 'C', 'C4', 'Doctor Fees', 1),
       (81, '01', 'Accommodation', 'F', 'F6', 'Room Rent', 1),
       (82, '02', 'Critical Care/ICU', 'F', 'F11', 'ICU Charges', 1),
       (83, '03', 'Operating Theatre', 'F', 'F4', 'OT Charges', 1),
       (84, '04', 'Surgeon Fees', 'F', 'F1', 'Professional Fees', 1),
       (85, '05', 'Anaesthetist Fees', 'F', 'F1', 'Anaesthesia Charges', 1),
       (86, '06', 'Implants', 'F', 'F8', 'Implants/ Prosthetic devices', 1),
       (87, '07', 'Medicines', 'F', 'F19', 'Medicines & Consumables', 1),
       (88, '08', 'Consumables', 'F', 'C19', 'Medicines & Consumables', 1),
       (89, '09', 'Special Equipment', 'F', 'F8', 'High Risk Charges', 1),
       (90, '10', 'In Patient Package', 'F', 'F8', 'surgical package', 1),
       (91, '13', 'Laboratory', 'F', 'F5', 'Investigation Charges', 1),
       (92, '14', 'Blood Bank', 'F', 'F5', 'Blood & Blood Products', 1),
       (93, '23', 'Consultation', 'F', 'F3', 'Investigation Charges', 1),
       (94, '33', 'Doctor\'s Visits', 'F', 'F3', 'Doctor Fees', 1),
       (95, '35', 'Ambulance', 'F', 'F7', 'Ambulance Charges', 1),
       (96, '41', 'Other', 'F', 'F8', 'Others', 1),
       (97, '01', 'Accommodation', 'N', 'N6', 'Room Rent', 1),
       (98, '02', 'Critical Care/ICU', 'N', 'N11', 'ICU Charges', 1),
       (99, '03', 'Operating Theatre', 'N', 'N4', 'OT Charges', 1),
       (100, '04', 'Surgeon Fees', 'N', 'N1', 'Professional Fees', 1),
       (101, '05', 'Anaesthetist Fees', 'N', 'N1', 'Anaesthesia Charges', 1),
       (102, '06', 'Implants', 'N', 'N8', 'Implants/ Prosthetic devices', 1),
       (103, '07', 'Medicines', 'N', 'N2', 'Medicines & Consumables', 1),
       (104, '08', 'Consumables', 'N', 'N2', 'Medicines & Consumables', 1),
       (105, '09', 'Special Equipment', 'N', 'N8', 'High Risk Charges', 1),
       (106, '10', 'In Patient Package', 'N', 'N9', 'surgical package', 1),
       (107, '13', 'Laboratory', 'N', 'N5', 'Investigation Charges', 1),
       (108, '14', 'Blood Bank', 'N', 'N5', 'Blood & Blood Products', 1),
       (109, '23', 'Consultation', 'N', 'N3', 'Investigation Charges', 1),
       (110, '33', 'Doctor\'s Visits', 'N', 'N3', 'Doctor Fees', 1),
       (111, '35', 'Ambulance', 'N', 'N7', 'Ambulance Charges', 1),
       (112, '41', 'Other', 'N', 'N8', 'Others', 1),
       (113, '10', 'In Patient Package', 'A', 'A9', 'Procedure Charges', 1),
       (114, '10', 'In Patient Package', 'C', 'C9', 'Procedure Charges', 1),
       (115, '10', 'In Patient Package', 'F', 'F8', 'Procedure Charges', 1),
       (116, '10', 'In Patient Package', 'N', 'N9', 'Procedure Charges', 1),
       (117, '10', 'In Patient Package', 'A', 'A9', 'Hospital SOC Package Charges', 1),
       (118, '10', 'In Patient Package', 'C', 'C9', 'Hospital SOC Package Charges', 1),
       (119, '10', 'In Patient Package', 'F', 'F8', 'Hospital SOC Package Charges', 1),
       (120, '10', 'In Patient Package', 'N', 'N9', 'Hospital SOC Package Charges', 1);
