CREATE TABLE bill_module_saving (
                                    id BIGINT PRIMARY KEY AUTO_INCREMENT,
                                    claim_data_id VARCHAR(255) NOT NULL,
                                    is_package_claim BOOLEAN,
                                    no_of_line_items INT,
                                    requested_amount DECIMAL(19, 2),
                                    insurer_requested_amount DECIMAL(19, 2),
                                    approved_amount DECIMAL(19, 2),
                                    insurer_approved_amount DECIMAL(19, 2),
                                    tariff_savings DECIMAL(19, 2),
                                    non_payable_savings DECIMAL(19, 2),
                                    construct_savings DECIMAL(19, 2),
                                    pharmacy_savings DECIMAL(19, 2),
                                    vneuron_savings DECIMAL(19, 2),
                                    insurer_tariff_savings DECIMAL(19, 2),
                                    insurer_non_payable_savings DECIMAL(19, 2),
                                    insurer_construct_savings DECIMAL(19, 2),
                                    insurer_pharmacy_savings DECIMAL(19, 2),
                                    insurer_vneuron_savings DECIMAL(19, 2),
                                    mou_savings DECIMAL(19, 2),
                                    sublimit_savings DECIMAL(19, 2),
                                    copay_savings DECIMAL(19, 2),
                                    proportional_discount DECIMAL(19, 2),
                                    stage VARCHAR(255),
                                    pml_review_reason TEXT,
                                    vneuron_review_reason TEXT,
                                    is_insurer_edit BOOLEAN,
                                    insurer_remark TEXT,
                                    parsed_percentage VARCHAR(30),
                                    rerun_count INT DEFAULT 0,
                                    change_code VARCHAR(30),
                                    date_created VARCHAR(30),
                                    date_updated VARCHAR(30),
                                    created_by VARCHAR(30),
                                    updated_by VARCHAR(30)
);