CREATE TABLE bill_line_item_saving_audit (
                                       backup_id BIGINT AUTO_INCREMENT PRIMARY KEY,
                                       id BIGINT,
                                       bill_module_id BIGINT,
                                       category_id BIGINT,
                                       row_id INT,
                                       line_item VARCHAR(255),
                                       requested_amount DECIMAL(19,2),
                                       insurer_requested_amount DECIMAL(19,2),
                                       approved_amount DECIMAL(19,2),
                                       insurer_approved_amount DECIMAL(19,2),
                                       tariff_savings DECIMAL(19,2),
                                       non_payable_savings DECIMAL(19,2),
                                       construct_savings DECIMAL(19,2),
                                       pharmacy_savings DECIMAL(19,2),
                                       vneuron_savings DECIMAL(19,2),
                                       insurer_tariff_savings DECIMAL(19,2),
                                       insurer_non_payable_savings DECIMAL(19,2),
                                       insurer_construct_savings DECIMAL(19,2),
                                       insurer_pharmacy_savings DECIMAL(19,2),
                                       insurer_vneuron_savings DECIMAL(19,2),
                                       mou_savings DECIMAL(19,2),
                                       sublimit_savings DECIMAL(19,2),
                                       copay_savings DECIMAL(19,2),
                                       proportional_discount DECIMAL(19, 2),
                                       deleted BOOLEAN DEFAULT FALSE,
                                       added BOOLEAN DEFAULT FALSE,
                                       edited BOOLEAN DEFAULT FALSE,
                                       status VARCHAR(30),
                                       rerun_count INT DEFAULT 0,
                                       change_code VARCHAR(30),
                                       date_created VARCHAR(30),
                                       date_updated VARCHAR(30),
                                       created_by VARCHAR(30),
                                       updated_by VARCHAR(30)
);
