package com.vitraya.adjudication.engine.dto.enums;

public enum ClaimRunIdentifier {
    FRESH_CLAIM_RUN,
    FRESH_EMAIL_CLAIM_RUN,
    NON_VERIFIED_EMAIL_CLAIM_RUN,
    API_FAILURE_EMAIL_CLAIM_RUN,
    NON_ADJUDICATION_CLAIM_RUN,
    NON_ADJUDICATION_EMAIL_CLAIM_RUN,
    CLAIM_RERUN,
    FRESH_CLAIM_BILL_TARIFF_RUN,
    CLAIM_BILL_TARIFF_QC_RESPONSE,
    RERUN_BILL_TARIFF,
    RERUN_BILL_TARIFF_PML,
    FRESH_CLAIM_PML_RUN,
    RERUN_PML,
    FRESH_CLAIM_VNEURON_RUN,
    RERUN_VNEURON,
    CRON_JOB,
    RERUN_TARIFF,
    RERUN_TARIFF_PML;
}
