package com.vitraya.adjudication.engine.dto.enums;

public enum EnhancementStatus {
    ENHANCEMENT_REQ_RECEIVED,
    ENHANCEMENT_AWAITED,
    ENHANCEMENT_IN_PROGRESS,
    ENHANCEMENT_SUCCESSFUL,
    ENHANCEMENT_FAILED,
    ENHANCEMENT_COMPLETED,
    OUT_OF_SCOPE_HOSPITAL,
    OUT_OF_SCOPE_CLAIM_STAGE,
    RELEVANT_DOCUMENT_NOT_FOUND,
    MANUAL_QC;
}
