package com.vitraya.adjudication.engine.dto.response;

import com.vitraya.adjudication.engine.dto.enums.*;
import com.vitraya.adjudication.engine.dto.request.PedDTO;
import com.vitraya.adjudication.engine.mysql.entity.*;
import lombok.Builder;
import lombok.Data;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

@Data
@Builder
public class ClaimDetailsResponseDTO {
    private String id;
    private String intimationNumber;
    private String preAuthId;
    private long hospitalId;
    private long insuranceAgencyId;
    private String insurerClaimIdentifier;
    private Date dateOfFirstDiagnosis;
    private String roomType;
    private ClaimType claimType;
    private String patientName;
    private int patientAge;
    private Date dateOfBirth;
    private boolean isEnhancementProcessed;
    private boolean isInsurerVisible;
    private boolean active;
    private boolean deleted;
    private Date dateCreated;
    private Date dateUpdated;
    private Date dateOfAdmission;
    private Date dateOfDischarge;
    private String hospitalName;
    private String hospitalCode;
    private String procedureName;
    private long procedureId;
    private String procedureCode;
    private String productName;
    private String productCode;
    private BigDecimal claimBillAmountRequested;
    private BigDecimal amountAfterTariffApplication;
    private BigDecimal amountAfterMedicalAdmissibility;
    private BigDecimal amountAfterPolicyrulesApplication;
    private BigDecimal amountDeductedInPercent;
    private BigDecimal amountApproved;
    private BigDecimal savings;
    private String billIdentifier;
    private String tariffIdentifier;
    private String medicalIdentifier;
    private String pmlIdentifier;
    private String vneuronRemarks;
    private ClaimVNeuronResponseStatus vneuronDecision;
    private List<TariffLineItemResponseDTO> tariffData;
    private Object pmlClaimResult; // ToDo : Need to change the type
    private BillTariffPmlDto tariffPmlDataMerged; // ToDo : Need to change the type
    private String combinedStatus;
    private Object enhancementStatus; // ToDo : Need to change the type
    private Object moduleStatus; // ToDo : Need to change the type
    private String adjudicationStatus;
    private BigDecimal tariffMatchPercentage;
    private TreatmentType treatmentType;
    private ClaimTransactionType claimTransactionType;
    private Date policyInceptionDate;
    private Date policyEndDate;
    private Date policyStartDate;
    private boolean isPMLSuccess;
    private boolean outOfScopeHospital;
    private BigDecimal billParsedConfig;
    private String policyNumber;
    private Date responseSentTime;
    private String claimStatus;
    private String policyVariant;
    private String claimRemarks;
    private String insurerRemarks;
    private String insurerStatus;
    private boolean isDischarge;
    private boolean isBillFound;
    private boolean billDocAvailable;
    private String reasonForHospitalization;
    private String illnessName;
    private String icdCode;
    private List<PedDTO> pedList;
    private boolean pushedToInsurer;
    private BigDecimal baseSumInsured;
    private BigDecimal remainingSumInsured;
    private Zone copayZone;
    private Zone hospitalZone;
    private String coverCode;
    private String claimTAT;
    private String moduleTAT;
    private String reverseFeedStatus;
    private boolean assigned;
    private String assignedBy;
    private DocumentsNameWithLocation documentsNameWithLocation;
    private String billS3Url;
    private String billName;
    private VNeuronResponseDTO vNeuronResponseDTO;
    private List<DocumentMaster> claimDocumentMaster;
    private long initialTat;
    private long dischargeTat;
    private boolean inScopeHospital;
    private boolean inScopePolicy;
    private boolean inScopeProcedure;
    private List<ClaimTransition> claimTransitions;
    private EnhancementStatus status;
    private String claimStage;
    private String preAuthInsurerDecision;
    private String dischargeInsurerDecision;
    private boolean claimRerun;
    private String token;
    private String claimRejectionReason;
    private String queryText;
    private BigDecimal billRequestedAmount;
    private BigDecimal billApprovedAmount;
    private BigDecimal billSavedAmount;
    private List<Procedures> procedureList;
    private List<HospitalServiceType> hospitalServiceTypeList;
    private BigDecimal patientPayableDeductable;
    private BigDecimal hospitalPayableDeductable;
    private boolean receivedReverseFeed;
    private boolean emailClaim;
    private boolean ucrApplied;
    private BigDecimal ucrApprovedAmount;
    private ClaimRiderDetails claimRiderDetails;
    private List<ErrorMessageLogs> errorMessageLogsList;
    private List<RiderDetails> ridersDetails;
}
